/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasasIndexRouteImport } from './routes/casas/index'
import { Route as CasasMarRouteImport } from './routes/casas/mar'
import { Route as CasasFilmRouteImport } from './routes/casas/film'
import { Route as CasasCascadaRouteImport } from './routes/casas/cascada'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasIndexRoute = CasasIndexRouteImport.update({
  id: '/casas/',
  path: '/casas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasMarRoute = CasasMarRouteImport.update({
  id: '/casas/mar',
  path: '/casas/mar',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasFilmRoute = CasasFilmRouteImport.update({
  id: '/casas/film',
  path: '/casas/film',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasCascadaRoute = CasasCascadaRouteImport.update({
  id: '/casas/cascada',
  path: '/casas/cascada',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/experiencias': typeof ExperienciasRoute
  '/galeria': typeof GaleriaRoute
  '/reservas': typeof ReservasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/casas/cascada': typeof CasasCascadaRoute
  '/casas/film': typeof CasasFilmRoute
  '/casas/mar': typeof CasasMarRoute
  '/casas/': typeof CasasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/experiencias': typeof ExperienciasRoute
  '/galeria': typeof GaleriaRoute
  '/reservas': typeof ReservasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/casas/cascada': typeof CasasCascadaRoute
  '/casas/film': typeof CasasFilmRoute
  '/casas/mar': typeof CasasMarRoute
  '/casas': typeof CasasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/experiencias': typeof ExperienciasRoute
  '/galeria': typeof GaleriaRoute
  '/reservas': typeof ReservasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/casas/cascada': typeof CasasCascadaRoute
  '/casas/film': typeof CasasFilmRoute
  '/casas/mar': typeof CasasMarRoute
  '/casas/': typeof CasasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/experiencias'
    | '/galeria'
    | '/reservas'
    | '/sitemap.xml'
    | '/casas/cascada'
    | '/casas/film'
    | '/casas/mar'
    | '/casas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/experiencias'
    | '/galeria'
    | '/reservas'
    | '/sitemap.xml'
    | '/casas/cascada'
    | '/casas/film'
    | '/casas/mar'
    | '/casas'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/experiencias'
    | '/galeria'
    | '/reservas'
    | '/sitemap.xml'
    | '/casas/cascada'
    | '/casas/film'
    | '/casas/mar'
    | '/casas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ExperienciasRoute: typeof ExperienciasRoute
  GaleriaRoute: typeof GaleriaRoute
  ReservasRoute: typeof ReservasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CasasCascadaRoute: typeof CasasCascadaRoute
  CasasFilmRoute: typeof CasasFilmRoute
  CasasMarRoute: typeof CasasMarRoute
  CasasIndexRoute: typeof CasasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/': {
      id: '/casas/'
      path: '/casas'
      fullPath: '/casas/'
      preLoaderRoute: typeof CasasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/mar': {
      id: '/casas/mar'
      path: '/casas/mar'
      fullPath: '/casas/mar'
      preLoaderRoute: typeof CasasMarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/film': {
      id: '/casas/film'
      path: '/casas/film'
      fullPath: '/casas/film'
      preLoaderRoute: typeof CasasFilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas/cascada': {
      id: '/casas/cascada'
      path: '/casas/cascada'
      fullPath: '/casas/cascada'
      preLoaderRoute: typeof CasasCascadaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ExperienciasRoute: ExperienciasRoute,
  GaleriaRoute: GaleriaRoute,
  ReservasRoute: ReservasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CasasCascadaRoute: CasasCascadaRoute,
  CasasFilmRoute: CasasFilmRoute,
  CasasMarRoute: CasasMarRoute,
  CasasIndexRoute: CasasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
